#!/usr/bin/python3


def raise_exception():
    a = 8
    b = '8'
    result = a + b
